name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    services:
      postgres:
        # Docker Hub image
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Checkout pgtap
      uses: actions/checkout@v2
      with:
        repository: theory/pgtap
        path: pgtap
    - name: install pgtap
      working-directory: pgtap
      run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
      env:
        PGPASSWORD: postgres
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: apt update and install
      run: |
        sudo apt -y -qq update
        sudo apt-get -y -qq install postgresql-client-common
    - name: Install
      run: |
        python -m pip install --user .[dev]
        make install
    - name: Run python tests
      run: |
        pytest -x -v --durations=10

