name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: 'pip'
        ache-dependency-path: "setup.py"
    - name: Run python test
      run: pytest tests
    - name: Build postgres docker image
      run: make docker
    - name: Run postgres tests
      run: make test
